import mongoose, { Schema } from "mongoose";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";

const userSchema = new Schema(
  {
    username: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
    },
    fullname: { type: String, required: true, trim: true, index: true },
    avatar: {
      type: String, //cloudinary url
      required: true,
    },
    coverImage: {
      type: String, //cloudinary url
    },
    watchHistory: [
      {
        type: Schema.Types.ObjectId,
        ref: "Video",
      },
    ],
    password: {
      type: String,
      required: [true, "Password is required"],
    },
    refeshToken: {
      type: String,
    },
  },
  { timestamps: true }
);

// mongoose pre-save hook to hash password before saving user document
// note: do not use arrow function here to access 'this' keyword
// as we will need referemce to data to manipulate before saving which we will get using 'this'
// so use normal function
// passing next to indicate when to move to next middleware in the chain,
// this function middleware in itself
userSchema.pre("save", async function (next) {
  // only hash the password if it has been modified or is new
  // so check password field is modified or not
  if (!this.isModified("password")) return next();

  //genereate salt with 10 rounds
  //   const salt = await bcrypt.genSalt(10); // generated by copilot
  //   this.password = await bcrypt.hash(this.password, salt);
  this.password = await bcrypt.hash(this.password, 10);
  next();
});

// mongoose gives option to create methods on schema just like pre and post hooks/middlewares
userSchema.methods.isPasswordCorrect = async function (password) {
  return await bcrypt.compare(password, this.password); //returns boolean
};

userSchema.methods.generateAccessToken = function () {
  return jwt.sign(
    {
      _id: this._id,
      email: this.email,
      username: this.username,
      fullname: this.fullname,
    },
    process.env.ACCESS_TOKEN_SECRET,
    {
      expiresIn: process.env.ACCESS_TOKEN_EXPIRY,
    }
  );
};

userSchema.methods.generateRefreshToken = function () {
  return jwt.sign(
    {
      _id: this._id,
    },
    process.env.REFRESH_TOKEN_SECRET,
    {
      expiresIn: process.env.REFRESH_TOKEN_EXPIRY,
    }
  );
};

export const User = mongoose.model("User", userSchema);
